# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f55cac42f931b4ec9f004e8eb85f3e755b582619eb4c62c49a86d15e6205942f1ceb0ef8ee8900fc1b7a6345a8cf48b922a703a7c74b58a3cade30c21468b4

test:
  secret_key_base: 809efc6a25bc974bc87340288ae90613f8e1de3e9735e1b032dc7b6aac840e257c1ab55dbf9d449eb6888526db54bfbcd807cf35e40fb9cf18eed6934cc4c35b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
