# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60636998466b58fdc3f2176750efced3b510905957ce9c033eb29b6b0ded58aec422584b2464fb36c3af80eaecf482586f94ca00664ad9aa4fcf7d4ab61fa8da

test:
  secret_key_base: 27e0fdb49c6bd89f6cbfa4df0aa79bf94c959d405c011f74aa09f270bfec003541e29e233d77e08d3deba7c9141ff7c3a0f0142fa72ca55469b7369b3461765f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
