# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176b50a48604b5cbbe5a3d2489f29266e1158c1133b04a0501d6663454dbf4afa3ecb63c71ab96b723680ce9ee66168a43e37a65d73c47665c3e59b926a0b277

test:
  secret_key_base: 4de471214aea392c69499c12f0261550e305d75a41cd5c8cf0d3d6a0d8efeac5002c38a57bc61ff88cf79ec255000ea8c8481541854fbc654bc83b9d8a5c08b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
